export const path = {
  HOME: "/*",
  LOGIN: "login",
  HEADER: "/header",
  STORAGE: "/admin/table/storage",
  DRINK: "/admin/table/drink",
  STAFF: "/admin/table/staff",
  ROLE: "/admin/table/role",
  RECIPE: "/admin/table/recipe",
  COFFEETOOLS: "/admin/table/coffeetools",
  INGREDIENT: "/admin/table/ingredient",
  SHOPEQUIPMENT: "/admin/table/shopequipment",
  USER: "/admin/table/users",
  BILL: "/admin/table/bill",
  EQUIPTYPE: "/admin/table/equipmenttype",
  MENU: "/admin/table/menu",
  STATICTICAL: "/admin/table/statictical",
  STATICTICAL_STORAGE: "/admin/table/staticticalstorage",

  API_BASE_URL: "http://localhost:5000",
  STAFF_API_URL: "/staff",
  DRINK_API_URL: "/drinks",
  INGREDIENT_API_URL: "/ingredient",
  STORAGE_API_URL: "/storage",
  DELETED_STORAGE_API_URL: "/storage/softDelete",
  ROLE_API_URL: "/role",
  COFFEETOOLS_API_URL: "/coffee-brewing-tools",
  SHOPEQUIPMENT_API_URL: "/shop-equipment",
  USER_API_URL: "/users",
  BILL_API_URL: "/bill",
  EQUIPTYPE_API_URL: "/equipment-type",
  AUTHOR_API_URL: "/auth/login",
  RECIPE_API_URL: "/drinks/drink-details",
  MENU_API_URL: "/menu",
  MENUDETAILS_API_URL: "/menu/menu_details",
};
